[package]
name = "kiana-commands"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"
anyhow = "1.0"
libc = "0.2"
sha2 = "0.10"
quick-xml = "0.41"
async-trait = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
kiana-bootstrap = { path = "../kiana-bootstrap", version = "0.1.0" }
kiana-modifiers = { path = "../kiana-modifiers", version = "0.1.0" }
kiana-query = { path = "../kiana-query", version = "0.1.0" }
kiana-services = { path = "../kiana-services", version = "0.1.0" }
kiana-skills = { path = "../kiana-skills", version = "0.1.0" }
kiana-tasks = { path = "../kiana-tasks", version = "0.1.0" }
kiana-tools = { path = "../kiana-tools", version = "0.1.0" }
kiana-types = { path = "../kiana-types", version = "0.1.0" }
