//! Kiana ControlPlane 使用的稳定领域契约。
//!
//! 本 crate 位于依赖图底层，定义 ID、角色/部门、WorkPacket、能力请求、审批、事件和
//! 生命周期等值对象，以及跨层共享的文本脱敏原语，不依赖 daemon、query 或具体执行器。
//! 结构体的序列化形状是跨模块的契约，但“存在一个类型”不等于运行时已经强制：真正的
//! 授权顺序、CAS、lease 和持久证据仍由 core 与 ports 的实现负责。
//!
//! 所有路径、能力和状态 helper 都采用收紧/拒绝优先的语义。调用方应把 `None`、拒绝和
//! `ResultUnknown` 与“没有副作用”严格区分，并以 EventLog/Receipt 作为事实来源，不把
//! transcript、UI 投影或模型自述当作状态权威。

mod adapter_result;
mod approval_journal;
mod approval_preview;
mod artifact_contracts;
mod assignment;
mod audit;
mod authority;
mod billing_admission;
mod billing_allocation;
mod billing_projection;
mod billing_budgets;
mod billing_contracts;
mod billing_cost;
mod billing_ledger;
mod billing_pricing;
mod billing_quota;
mod billing_reservation;
mod billing_settlement_fold;
mod billing_usage;
mod billing_usage_accumulator;
mod budget_contracts;
mod cancellation;
mod capabilities;
mod capability_catalog;
mod capability_conformance;
mod control_plane_authority;
mod control_plane_product_flow;
mod er31_fault_matrix;
mod er32_adapter_conformance;
mod er33_capacity_migration;
mod er34_durable_gate;
mod ci12_product_gate;
mod automation_snapshot;
mod automation_surface_uat;
mod automation_release_evidence;
mod child_harness;
mod chunk_provenance;
mod clarification;
mod clock;
mod code_graph;
mod communication;
mod compact_summary;
mod compaction_commit;
pub mod company;
mod company_policy;
mod company_receipts;
mod company_replay;
mod company_scope;
mod company_proposals;
mod connector_credentials;
mod connector_cancellation;
mod connector_dispatch;
mod connector_effect_permit;
mod connector_fixture;
mod connector_https;
mod connector_operation;
mod connector_policy;
mod connector_protocol;
mod connector_reservation;
mod connector_quota;
mod connector_registry;
mod connector_reconciliation;
mod connector_retry;
mod connector_scope;
mod connectors;
mod container_inventory;
mod container_lifecycle_evidence;
mod context_checkpoint;
mod context_invalidation;
mod context_memory_evidence;
mod context_plan;
mod context_scope;
mod contracts;
mod criteria;
mod cost_correction;
mod credential_recovery_evidence;
mod credentials;
mod deletion;
mod department_packets;
mod embedding_manifest;
mod errors;
mod eval;
mod event_contracts;
mod execution_identity;
mod execution_output;
mod execution_scope;
mod extension_adapters;
mod extension_catalog;
mod extension_commands;
mod extension_contracts;
mod extension_lifecycle;
mod extension_golden;
mod extension_recovery;
mod extension_release;
mod extension_state;
mod extension_visibility;
mod extensions;
mod external_resource;
mod fault;
mod fallback_admission;
mod fencing;
mod golden_context;
mod governance_gate;
mod grant_authority;
mod harness_eval;
mod harness_integration;
mod hook_lifecycle;
mod identity;
mod identity_contracts;
mod image_input;
mod ids;
mod inbox_contract;
mod index_generation;
mod index_invalidation;
mod inspector;
mod invocation_resume;
mod job_handle;
mod legacy_compat;
mod live_handoff;
mod local_rollout;
mod mcp_connector;
mod memory;
mod memory_acl;
mod memory_distillation;
mod memory_extraction;
mod memory_invalidation;
mod memory_journal;
mod memory_mutation;
mod memory_negative_gate;
mod memory_maintenance;
mod memory_projection;
mod memory_proposals;
mod memory_temporal;
mod memory_workbench;
mod migration_preflight;
mod migration_primitives;
mod migration_rebuild;
mod migration_record;
mod migration_registry;
mod migration_rollback;
mod migration_runner;
mod model_attempt_lifecycle;
mod network_policy;
mod notification_events;
mod notification_policy;
mod notification_recovery;
mod notification_external;
mod notification_faults;
mod notification_parity;
mod notifications;
mod notification_outbox;
mod notification_actions;
mod notification_lifecycle;
mod oauth;
mod oauth_accounts;
mod orchestrated_rollout;
mod orchestrated_rollout_evidence;
mod parity;
mod paths;
mod performance;
mod persistence_capacity;
mod persistence_capacity_evidence;
mod persistence_uat;
mod persistence_uat_evidence;
mod platform;
mod platform_backend;
mod process_supervisor;
mod progress_stall;
mod projection_contracts;
mod projection_recovery;
mod prompts;
mod protected_replay;
mod provider_config;
mod provider_capacity;
mod provider_contracts;
mod provider_diagnostics;
mod provider_product_chain;
mod provider_recovery;
mod provider_live;
mod provider_usage_settlement;
mod quality;
mod receipt_aggregation;
mod receipt_contracts;
mod recovery_resources;
mod redaction;
mod release_attestation;
mod release_preflight;
mod release_uat;
mod release_uat_evidence;
mod repo_map_task;
mod request_budget;
mod request_compilation;
mod resource_cleanup;
mod resource_leases;
mod retention;
mod retention_watermark;
mod retrieval_context;
mod retrieval_evaluation;
mod retrieval_evidence;
mod retrieval_receipt;
mod retry_policy;
mod revision_compatibility;
mod roles;
mod rollout_lifecycle;
mod rollout_lifecycle_evidence;
mod route_attestation;
mod runtime_evidence;
mod scope;
mod security_contracts;
mod security_reasons;
mod security_rehearsal;
mod session_contracts;
mod snapshot_manifest;
mod source_dependencies;
mod states;
mod storage;
mod storage_health;
mod storage_schema;
mod storage_security;
mod supply_chain;
mod supply_chain_release_evidence;
mod swarm_graph;
mod swarm_identity;
mod swarm_reducer;
mod symposiums;
mod symposium_governance;
mod symposium_runtime;
#[cfg(test)]
mod tests;
mod text_normalization;
mod tool_output_spill;
mod tool_scheduling;
mod trust_snapshots;
mod turn_outcome;
mod ui_action;
mod ui_snapshot;
mod unified_retrieval;
mod usage;
mod versioning;
mod work_packets;
mod workflow_event_ingress;
mod workflow_queue_claim;
mod workflow_queue_lease;
mod workspace_snapshot;

pub use adapter_result::*;
pub use approval_journal::*;
pub use approval_preview::*;
pub use artifact_contracts::*;
pub use assignment::*;
pub use audit::*;
pub use authority::*;
pub use billing_admission::*;
pub use billing_allocation::*;
pub use billing_projection::*;
pub use billing_budgets::*;
pub use billing_contracts::*;
pub use billing_cost::*;
pub use billing_ledger::*;
pub use billing_pricing::*;
pub use billing_quota::*;
pub use billing_reservation::*;
pub use billing_settlement_fold::*;
pub use billing_usage::*;
pub use billing_usage_accumulator::*;
pub use budget_contracts::*;
pub use cancellation::*;
pub use capabilities::*;
pub use capability_catalog::*;
pub use capability_conformance::*;
pub use control_plane_authority::*;
pub use control_plane_product_flow::*;
pub use er31_fault_matrix::*;
pub use er32_adapter_conformance::*;
pub use er33_capacity_migration::*;
pub use er34_durable_gate::*;
pub use ci12_product_gate::*;
pub use automation_snapshot::*;
pub use automation_surface_uat::*;
pub use automation_release_evidence::*;
pub use child_harness::*;
pub use chunk_provenance::*;
pub use clarification::*;
pub use clock::*;
pub use code_graph::*;
pub use communication::*;
pub use compact_summary::*;
pub use compaction_commit::*;
pub use company::*;
pub use company_policy::*;
pub use company_receipts::*;
pub use company_replay::*;
pub use company_scope::*;
pub use company_proposals::*;
pub use connector_credentials::*;
pub use connector_cancellation::*;
pub use connector_dispatch::*;
pub use connector_effect_permit::*;
pub use connector_fixture::*;
pub use connector_https::*;
pub use connector_operation::*;
pub use connector_policy::*;
pub use connector_protocol::*;
pub use connector_reservation::*;
pub use connector_quota::*;
pub use connector_registry::*;
pub use connector_reconciliation::*;
pub use connector_retry::*;
pub use connector_scope::*;
pub use connectors::*;
pub use container_inventory::*;
pub use container_lifecycle_evidence::*;
pub use context_checkpoint::*;
pub use context_invalidation::*;
pub use context_memory_evidence::*;
pub use context_plan::*;
pub use context_scope::*;
pub use contracts::*;
pub use criteria::*;
pub use credential_recovery_evidence::*;
pub use credentials::*;
pub use deletion::*;
pub use department_packets::*;
pub use embedding_manifest::*;
pub use errors::*;
pub use eval::*;
pub use event_contracts::*;
pub use execution_identity::*;
pub use execution_output::*;
pub use execution_scope::*;
pub use extension_adapters::*;
pub use extension_catalog::*;
pub use extension_commands::*;
pub use extension_contracts::*;
pub use extension_lifecycle::*;
pub use extension_golden::*;
pub use extension_recovery::*;
pub use extension_release::*;
pub use extension_state::*;
pub use extension_visibility::*;
pub use extensions::*;
pub use external_resource::*;
pub use fault::*;
pub use fallback_admission::*;
pub use fencing::*;
pub use golden_context::*;
pub use governance_gate::*;
pub use grant_authority::*;
pub use harness_eval::*;
pub use harness_integration::*;
pub use hook_lifecycle::*;
pub use identity::*;
pub use identity_contracts::*;
pub use image_input::*;
pub use ids::*;
pub use inbox_contract::*;
pub use index_generation::*;
pub use index_invalidation::*;
pub use inspector::*;
pub use invocation_resume::*;
pub use job_handle::*;
pub use legacy_compat::*;
pub use live_handoff::*;
pub use local_rollout::*;
pub use mcp_connector::*;
pub use memory::*;
pub use memory_acl::*;
pub use memory_distillation::*;
pub use memory_extraction::*;
pub use memory_invalidation::*;
pub use memory_journal::*;
pub use memory_mutation::*;
pub use memory_negative_gate::*;
pub use memory_maintenance::*;
pub use memory_projection::*;
pub use memory_proposals::*;
pub use memory_temporal::*;
pub use memory_workbench::*;
pub use migration_preflight::*;
pub use migration_primitives::*;
pub use migration_rebuild::*;
pub use migration_record::*;
pub use migration_registry::*;
pub use migration_rollback::*;
pub use migration_runner::*;
pub use model_attempt_lifecycle::*;
pub use network_policy::*;
pub use notification_events::*;
pub use notification_policy::*;
pub use notification_recovery::*;
pub use notification_external::*;
pub use notification_faults::*;
pub use notification_parity::*;
pub use notifications::*;
pub use notification_outbox::*;
pub use notification_actions::*;
pub use notification_lifecycle::*;
pub use oauth::*;
pub use oauth_accounts::*;
pub use orchestrated_rollout::*;
pub use orchestrated_rollout_evidence::*;
pub use parity::*;
pub use paths::*;
pub use performance::*;
pub use persistence_capacity::*;
pub use persistence_capacity_evidence::*;
pub use persistence_uat::*;
pub use persistence_uat_evidence::*;
pub use platform::*;
pub use platform_backend::*;
pub use process_supervisor::*;
pub use progress_stall::*;
pub use projection_contracts::*;
pub use projection_recovery::*;
pub use prompts::*;
pub use protected_replay::*;
pub use provider_config::*;
pub use provider_capacity::*;
pub use provider_contracts::*;
pub use provider_diagnostics::*;
pub use provider_product_chain::*;
pub use provider_recovery::*;
pub use provider_live::*;
pub use provider_usage_settlement::*;
pub use quality::*;
pub use receipt_aggregation::*;
pub use receipt_contracts::*;
pub use recovery_resources::*;
pub use redaction::*;
pub use release_attestation::*;
pub use release_preflight::*;
pub use release_uat::*;
pub use release_uat_evidence::*;
pub use repo_map_task::*;
pub use request_budget::*;
pub use request_compilation::*;
pub use resource_cleanup::*;
pub use resource_leases::*;
pub use retention::*;
pub use retention_watermark::*;
pub use retrieval_context::*;
pub use retrieval_evaluation::*;
pub use retrieval_evidence::*;
pub use retrieval_receipt::*;
pub use retry_policy::*;
pub use revision_compatibility::*;
pub use roles::*;
pub use rollout_lifecycle::*;
pub use rollout_lifecycle_evidence::*;
pub use route_attestation::*;
pub use runtime_evidence::*;
pub use scope::*;
pub use security_contracts::*;
pub use security_reasons::*;
pub use security_rehearsal::*;
pub use session_contracts::*;
pub use snapshot_manifest::*;
pub use source_dependencies::*;
pub use states::*;
pub use storage::*;
pub use storage_health::*;
pub use storage_schema::*;
pub use storage_security::*;
pub use supply_chain::*;
pub use supply_chain_release_evidence::*;
pub use swarm_graph::*;
pub use swarm_identity::*;
pub use swarm_reducer::*;
pub use symposiums::*;
pub use symposium_governance::*;
pub use symposium_runtime::*;
pub use text_normalization::*;
pub use tool_output_spill::*;
pub use tool_scheduling::*;
pub use trust_snapshots::*;
pub use turn_outcome::*;
pub use ui_action::*;
pub use ui_snapshot::*;
pub use unified_retrieval::*;
pub use usage::*;
pub use versioning::*;
pub use work_packets::*;
pub use workflow_event_ingress::*;
pub use workflow_queue_claim::*;
pub use workflow_queue_lease::*;
pub use workspace_snapshot::*;

pub const APPROVAL_CHALLENGE_SCHEMA: &str = "kiana.approval-challenge.v1";
pub const ROLE_BUILDER: &str = "builder";
pub const ROLE_PM: &str = "pm";
pub const ROLE_ARCHITECT: &str = "architect";
pub const ROLE_REVIEWER: &str = "reviewer";
pub const ROLE_SPONSOR: &str = "sponsor";
pub const ROLE_CLOSER: &str = "closer";
pub const ROLE_ANALYST: &str = "analyst";
pub const ROLE_QA: &str = "qa";
pub const ROLE_LIBRARIAN: &str = "librarian";
pub const ROLE_SPEC_SCHEMA: &str = "kiana.role-spec.v1";
pub const ROLE_CATALOG_SCHEMA: &str = "kiana.role-catalog.v1";
pub const DEPARTMENT_SPEC_SCHEMA: &str = "kiana.department-spec.v1";
pub const DEPARTMENT_CATALOG_SCHEMA: &str = "kiana.department-catalog.v1";
pub const ROLE_INPUT_SCHEMA_PREFIX: &str = "kiana.company-role-input";
pub const ROLE_OUTPUT_SCHEMA_PREFIX: &str = "kiana.company-role-output";
pub const DEPARTMENT_EXECUTING: &str = "executing";
pub const DEPARTMENT_PLANNING: &str = "planning";
pub const DEPARTMENT_MONITORING: &str = "monitoring";
pub const DEPARTMENT_INITIATING: &str = "initiating";
pub const DEPARTMENT_CLOSING: &str = "closing";
pub const ROLE_SANDBOX_READ_ONLY: &str = "read-only";
pub const ROLE_SANDBOX_WORKSPACE_WRITE: &str = "workspace-write";
pub const PLANNING_PATH_CHARTER: &str = "charter";
pub const PLANNING_PATH_PLAN: &str = "plan";
pub const PLANNING_PATH_PACKET: &str = "packet";
pub const CLOSING_PATH_LESSONS: &str = "lessons";
pub const EXECUTING_PATH_RECEIPT: &str = "receipt";
pub const WORK_PACKET_SCHEMA: &str = "kiana.work-packet.v1";
pub const DECISION_RECORD_SCHEMA: &str = "kiana.decision-record.v1";
pub const SYMPOSIUM_SCHEMA: &str = "kiana.symposium.v1";
pub const SYMPOSIUM_RESULT_SCHEMA: &str = "kiana.symposium-result.v1";
pub const SYMPOSIUM_TYPE_DECISION: &str = "decision";
pub const SYMPOSIUM_STATUS_CLOSED: &str = "closed";
pub const SYMPOSIUM_STATUS_SKIPPED: &str = "skipped";
pub const DECISION_RECORD_PATH: &str = "plan/DECISION.json";
pub const INITIATING_DECISION_PATH: &str = "charter/DECISION.json";
pub const EXECUTING_DECISION_PATH: &str = "receipt/DECISION.json";
pub const MONITORING_DECISION_PATH: &str = "gate/DECISION.json";
pub const CLOSING_DECISION_PATH: &str = "lessons/DECISION.json";
pub const CLOSING_RECEIPT_PATH: &str = "lessons/CLOSING.json";
pub const WORK_PACKET_PATH: &str = "packet/TASK.json";
pub const REVIEW_PACKET_SCHEMA: &str = "kiana.review-packet.v1";
pub const REVIEW_RESULT_SCHEMA: &str = "kiana.review-result.v1";
pub const REVIEW_PACKET_PATH: &str = "gate/REVIEW.json";
pub const MERGE_RECEIPT_PATH: &str = "gate/MERGE.json";
pub const MONITORING_PATH_GATE: &str = "gate";
pub const MEMORY_LAYER_COMPANY: &str = "company";
pub const MEMORY_LAYER_DEPARTMENT: &str = "department";
pub const MEMORY_LAYER_ROLE: &str = "role";
pub const MEMORY_LAYER_PROJECT: &str = "project";
pub const MEMORY_LAYER_USER: &str = "user";
pub const MEMORY_LAYER_INSTANCE_SCRATCH: &str = "instance-scratch";
pub const MEMORY_COLLECTION_USER_PRIVATE: &str = "user-private";
pub const MEMORY_COLLECTION_USER_PREFS: &str = "user:prefs";
pub const MEMORY_COLLECTION_PLANNING_UNRELEASED: &str = "planning:unreleased-debate";
pub const MEMORY_SEARCH_SCHEMA: &str = "kiana.memory-search.v1";
pub const MEMORY_WRITE_SCHEMA: &str = "kiana.memory-write.v1";
pub const MEMORY_RECORD_SCHEMA: &str = "kiana.memory-record.v1";
pub const AGENT_TEMPLATE_SCHEMA: &str = "kiana.agent-template.v1";
pub const CELL_SCHEMA: &str = "kiana.cell.v1";
pub const SPAWN_PLAN_SCHEMA: &str = "kiana.spawn-plan.v1";
pub const BUDGET_LEASE_SCHEMA: &str = "kiana.budget-lease.v1";
pub const CAPABILITY_GRANT_SCHEMA: &str = "kiana.capability-grant.v1";
pub const SUPERVISION_LEASE_SCHEMA: &str = "kiana.supervision-lease.v1";
pub const DELEGATION_PACKET_SCHEMA: &str = "kiana.delegation-packet.v1";
pub const MERGE_RECEIPT_SCHEMA: &str = "kiana.merge-receipt.v1";
pub const CLOSING_RECEIPT_SCHEMA: &str = "kiana.closing-receipt.v1";
pub const SPAWN_RESULT_SCHEMA: &str = "kiana.spawn-result.v1";
pub const RETIREMENT_RECORD_SCHEMA: &str = "kiana.retirement-record.v1";
pub const MEMORY_LAYERS: [&str; 6] = [
    MEMORY_LAYER_COMPANY,
    MEMORY_LAYER_DEPARTMENT,
    MEMORY_LAYER_ROLE,
    MEMORY_LAYER_PROJECT,
    MEMORY_LAYER_USER,
    MEMORY_LAYER_INSTANCE_SCRATCH,
];

mod tool_authority;
mod tool_catalog;
pub use tool_authority::*;
pub use tool_catalog::*;
mod governance;
pub use governance::*;
mod packet_graph;
mod plan;
pub use packet_graph::*;
pub use plan::*;

mod automation;
pub use automation::*;

mod swarm;
pub use swarm::*;

mod handoff;
pub use handoff::*;
mod company_handoff;
pub use company_handoff::*;
mod company_readiness;
pub use company_readiness::*;
mod company_attempt;
pub use company_attempt::*;
mod cell_admission;
pub use cell_admission::*;
mod company_task_scope;
pub use company_task_scope::*;
mod company_process;
pub use company_process::*;
mod company_wake;
pub use company_wake::*;
mod company_evidence;
pub use company_evidence::*;
mod company_review;
pub use company_review::*;
mod packet_acceptance;
pub use packet_acceptance::*;
mod milestone_acceptance;
pub use milestone_acceptance::*;
mod project_acceptance;
pub use project_acceptance::*;
mod rework_contract;
pub use rework_contract::*;
mod change_contract;
pub use change_contract::*;
mod project_control;
pub use project_control::*;
mod company_reconciliation;
pub use company_reconciliation::*;
mod delivery_manifest;
pub use delivery_manifest::*;
mod delivery_authorization;
pub use delivery_authorization::*;
mod closing_receipt;
pub use closing_receipt::*;
mod outcome_measurement;
pub use outcome_measurement::*;
mod company_knowledge;
pub use company_knowledge::*;
mod company_read_model;
pub use company_read_model::*;
mod company_inbox;
pub use company_inbox::*;
mod company_recovery;
pub use company_recovery::*;
mod company_parallel;
pub use company_parallel::*;
mod company_integration;
pub use company_integration::*;
mod company_portfolio;
pub use company_portfolio::*;
mod company_template_registry;
pub use company_template_registry::*;

mod dispatch;
mod effect_observation;
mod effect_usage;
pub use dispatch::*;
pub use effect_observation::*;
pub use effect_usage::*;

mod journal;
pub use journal::*;

mod actions;
pub use actions::*;

mod company_business;
pub use company_business::*;

mod model;
mod model_catalog;
mod model_event;
pub use model::*;
pub use model_catalog::*;
pub use model_event::*;
mod observability;
pub use observability::*;
mod correlation;
pub use correlation::*;

mod company_closeout;
mod company_live_evidence;
pub use company_closeout::*;
pub use company_live_evidence::*;
