[package]
name = "kiana-color-diff"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
syntect = "5.2"
similar = { version = "2.6", features = ["inline"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ansi_term = "0.12"

[dev-dependencies]
