[package]
name = "kiana-components"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
