//! Generated by scripts/validate-ui09-schemas.py --write; do not edit by hand.
//!
//! JSON Schema remains canonical. This catalog only exposes bounded metadata to clients.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UiSchemaContract {
    pub id: &'static str,
    pub rust_type: &'static str,
    pub max_bytes: usize,
    pub unknown_fields: &'static str,
}

pub const UI_SCHEMA_LOCK_SCHEMA: &str = "kiana.ui-schema-lock.v1";

pub const UI_SCHEMA_CONTRACTS: &[UiSchemaContract] = &[
    UiSchemaContract {
        id: "kiana.ui-action-result.v1",
        rust_type: "UiActionResult",
        max_bytes: 65536,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-action.v1",
        rust_type: "UiActionV1",
        max_bytes: 65536,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-entity-store-snapshot.v1",
        rust_type: "UiEntityStoreSnapshot",
        max_bytes: 1048576,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-feed-frame.v1",
        rust_type: "UiFeedFrameV1",
        max_bytes: 262144,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-handshake-request.v1",
        rust_type: "UiHandshakeRequest",
        max_bytes: 32768,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-handshake-response.v1",
        rust_type: "UiHandshakeResponse",
        max_bytes: 65536,
        unknown_fields: "deny",
    },
    UiSchemaContract {
        id: "kiana.ui-snapshot.v1",
        rust_type: "UiSnapshotV1",
        max_bytes: 2097152,
        unknown_fields: "deny",
    },
];

pub fn schema_contract(id: &str) -> Option<&'static UiSchemaContract> {
    UI_SCHEMA_CONTRACTS
        .iter()
        .find(|contract| contract.id == id)
}
