[package]
name = "kiana-runner-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
kiana-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
