#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"
out="${KIANA_ENTITLEMENT_PROOF_OUT:-target/entitlement-proof/entitlement-proof.json}"
required_entitlements="${KIANA_REQUIRED_ENTITLEMENTS:-commercial-use,enterprise-support,managed-policy}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "entitlement proof report requires python3 or python" >&2
    exit 1
  }
}

if [[ "$mode" == "--local-rc" ]]; then
  ENTITLEMENT_PROOF_OUT="$out" \
    ENTITLEMENT_PROOF_VERSION="$version" \
    ENTITLEMENT_REQUIRED="$required_entitlements" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

report = {
    "schema": "kiana.entitlement-proof.v1",
    "version": os.environ["ENTITLEMENT_PROOF_VERSION"],
    "status": "local_rc_only",
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "account_id": "",
    "organization": "",
    "plan": "",
    "license_status": "missing",
    "entitlements": [
        item.strip()
        for item in os.environ["ENTITLEMENT_REQUIRED"].split(",")
        if item.strip()
    ],
    "license_key_fingerprint": "",
    "support_contact": "",
    "backend": {
        "name": "",
        "environment": "",
        "checked_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "request_id": "",
    },
    "notes": ["Generated by scripts/entitlement-proof-report.sh --local-rc"],
}
with open(os.environ["ENTITLEMENT_PROOF_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "entitlement proof local RC report written to $out"
  exit 0
fi

proof_file="${KIANA_ENTITLEMENT_PROOF_FILE:-docs/entitlements/${version}.json}"
if [[ ! -f "$proof_file" ]]; then
  echo "full entitlement proof requires KIANA_ENTITLEMENT_PROOF_FILE or ${proof_file}" >&2
  exit 1
fi

ENTITLEMENT_PROOF_FILE="$proof_file" \
ENTITLEMENT_PROOF_OUT="$out" \
ENTITLEMENT_PROOF_VERSION="$version" \
ENTITLEMENT_REQUIRED="$required_entitlements" \
"$(python_bin)" - <<'PY'
import json
import os
import shutil
import sys

source = os.environ["ENTITLEMENT_PROOF_FILE"]
out = os.environ["ENTITLEMENT_PROOF_OUT"]
version = os.environ["ENTITLEMENT_PROOF_VERSION"]
required_entitlements = {
    item.strip()
    for item in os.environ["ENTITLEMENT_REQUIRED"].split(",")
    if item.strip()
}

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

backend = report.get("backend")
if not isinstance(backend, dict):
    backend = {}

required_strings = [
    "accepted_by",
    "accepted_at",
    "account_id",
    "organization",
    "plan",
    "license_key_fingerprint",
    "support_contact",
]
backend_strings = ["name", "environment", "checked_at", "request_id"]
placeholder_markers = (
    "todo",
    "tbd",
    "pending",
    "placeholder",
    "replace-me",
    "example.com",
    "example.test",
)

def filled(mapping, key):
    value = mapping.get(key)
    return isinstance(value, str) and bool(value.strip())

def not_placeholder(mapping, key):
    value = mapping.get(key)
    return isinstance(value, str) and not any(
        marker in value.lower() for marker in placeholder_markers
    )

entitlements = set(report.get("entitlements") or [])
checks = [
    report.get("schema") == "kiana.entitlement-proof.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    report.get("license_status") == "active",
    all(filled(report, key) for key in required_strings),
    all(not_placeholder(report, key) for key in required_strings),
    required_entitlements.issubset(entitlements),
    all(filled(backend, key) for key in backend_strings),
    all(not_placeholder(backend, key) for key in backend_strings),
]
if not all(checks):
    print("entitlement proof file failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    if required_entitlements:
        print(
            "required_entitlements: "
            + ",".join(sorted(required_entitlements)),
            file=sys.stderr,
        )
    sys.exit(1)

shutil.copyfile(source, out)
print(f"entitlement proof accepted: {source} -> {out}")
PY
