#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"

platform_id() {
  case "$(uname -s)" in
    Linux*) printf 'linux' ;;
    Darwin*) printf 'macos' ;;
    MSYS*|MINGW*|CYGWIN*) printf 'windows' ;;
    *) printf 'unknown' ;;
  esac
}

platform="$(platform_id)"
if [[ "$platform" == "unknown" ]]; then
  echo "unsupported platform for security proof: $(uname -s)" >&2
  exit 1
fi

default_out="target/platform-security/platform-security-${platform}.json"
out="${KIANA_PLATFORM_SECURITY_PROOF_OUT:-$default_out}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "platform security proof report requires python3 or python" >&2
    exit 1
  }
}

isolation_for_platform() {
  case "$platform" in
    linux) printf 'linux_bwrap' ;;
    macos) printf 'macos_exec_policy' ;;
    windows) printf 'windows_exec_policy' ;;
  esac
}

if [[ "$mode" == "--local-rc" ]]; then
  PLATFORM_SECURITY_OUT="$out" \
    PLATFORM_SECURITY_VERSION="$version" \
    PLATFORM_SECURITY_PLATFORM="$platform" \
    PLATFORM_SECURITY_ISOLATION="$(isolation_for_platform)" \
    PLATFORM_SECURITY_RUNNER="${RUNNER_NAME:-${COMPUTERNAME:-${HOSTNAME:-local}}}" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

platform = os.environ["PLATFORM_SECURITY_PLATFORM"]
isolation = os.environ["PLATFORM_SECURITY_ISOLATION"]
report = {
    "schema": "kiana.platform-security-proof.v1",
    "version": os.environ["PLATFORM_SECURITY_VERSION"],
    "status": "local_rc_only",
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "platform": platform,
    "runner": os.environ["PLATFORM_SECURITY_RUNNER"],
    "isolation": isolation,
    "controls": [
        "permission_profile:commercial",
        "permission_mode:ask",
        "explicit_project_trust:required",
        "managed_allow_required_for_mutations",
        f"isolation:{isolation}",
        "network_policy:explicit-provider-credentials",
    ],
    "doctor_status": "unknown",
    "evidence": [
        {"label": "mode", "value": "local_rc_only"},
        {"label": "platform", "value": platform},
        {"label": "isolation", "value": isolation},
    ],
    "notes": [
        "Generated by scripts/platform-security-proof-report.sh --local-rc",
        "Full commercial release requires accepted proof from real release runners",
    ],
}
with open(os.environ["PLATFORM_SECURITY_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "platform security local RC report written to $out"
  exit 0
fi

proof_dir="${KIANA_PLATFORM_SECURITY_PROOF_DIR:-docs/platform-security}"
proof_file="${KIANA_PLATFORM_SECURITY_PROOF_FILE:-${proof_dir}/${version}-${platform}.json}"
if [[ ! -f "$proof_file" ]]; then
  echo "full platform security proof requires KIANA_PLATFORM_SECURITY_PROOF_FILE or ${proof_file}" >&2
  exit 1
fi

PLATFORM_SECURITY_FILE="$proof_file" \
PLATFORM_SECURITY_OUT="$out" \
PLATFORM_SECURITY_VERSION="$version" \
PLATFORM_SECURITY_PLATFORM="$platform" \
PLATFORM_SECURITY_ISOLATION="$(isolation_for_platform)" \
"$(python_bin)" - <<'PY'
import json
import os
import re
import shutil
import sys

source = os.environ["PLATFORM_SECURITY_FILE"]
out = os.environ["PLATFORM_SECURITY_OUT"]
version = os.environ["PLATFORM_SECURITY_VERSION"]
platform = os.environ["PLATFORM_SECURITY_PLATFORM"]
isolation = os.environ["PLATFORM_SECURITY_ISOLATION"]

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

placeholder_markers = (
    "todo",
    "tbd",
    "pending",
    "placeholder",
    "replace-me",
    "example.com",
    "example.test",
)

def filled(key):
    value = report.get(key)
    return isinstance(value, str) and bool(value.strip())

def not_placeholder(key):
    value = report.get(key)
    return isinstance(value, str) and not any(
        marker in value.lower() for marker in placeholder_markers
    )

controls = report.get("controls") or []
evidence = report.get("evidence") or []
evidence_labels = {
    item.get("label"): item.get("value")
    for item in evidence
    if isinstance(item, dict)
}
required_controls = {
    "permission_profile:commercial",
    "permission_mode:ask",
    "explicit_project_trust:required",
    "managed_allow_required_for_mutations",
    f"isolation:{isolation}",
    "network_policy:explicit-provider-credentials",
}

def valid_sha256(value):
    return isinstance(value, str) and re.fullmatch(r"[a-f0-9]{64}", value) is not None

checks = [
    report.get("schema") == "kiana.platform-security-proof.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    filled("accepted_by"),
    filled("accepted_at"),
    filled("runner"),
    filled("runner_id"),
    filled("generated_at"),
    filled("doctor_command"),
    not_placeholder("accepted_by"),
    not_placeholder("runner"),
    not_placeholder("runner_id"),
    not_placeholder("doctor_command"),
    report.get("platform") == platform,
    report.get("isolation") == isolation,
    report.get("doctor_status") == "ready",
    isinstance(controls, list) and len(controls) > 0,
    isinstance(evidence, list) and len(evidence) > 0,
    required_controls.issubset(set(controls)),
    valid_sha256(report.get("doctor_report_sha256")),
    evidence_labels.get("doctor_report_sha256") == report.get("doctor_report_sha256"),
    evidence_labels.get("doctor_command") == report.get("doctor_command"),
    evidence_labels.get("runner_id") == report.get("runner_id"),
]
if not all(checks):
    print("platform security proof failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    print(f"expected platform={platform} isolation={isolation}", file=sys.stderr)
    sys.exit(1)

shutil.copyfile(source, out)
print(f"platform security proof accepted: {source} -> {out}")
PY
