#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"
out="${KIANA_PRODUCT_ACCEPTANCE_OUT:-target/product-acceptance/product-acceptance.json}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "product acceptance report requires python3 or python" >&2
    exit 1
  }
}

bash scripts/product-shell-smoke.sh

if [[ "$mode" == "--local-rc" ]]; then
  PRODUCT_ACCEPTANCE_OUT="$out" \
    PRODUCT_ACCEPTANCE_VERSION="$version" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

report = {
    "schema": "kiana.product-acceptance.v1",
    "version": os.environ["PRODUCT_ACCEPTANCE_VERSION"],
    "status": "headless_smoke_only",
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "scope": "headless product-shell smoke only; target-customer terminal acceptance is still required",
    "workflows": [
        "permission",
        "diff",
        "history",
        "onboarding",
        "resume",
        "settings",
    ],
    "notes": ["Generated by scripts/product-acceptance-report.sh --local-rc"],
}
with open(os.environ["PRODUCT_ACCEPTANCE_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "product acceptance local RC report written to $out"
  exit 0
fi

acceptance_file="${KIANA_PRODUCT_ACCEPTANCE_FILE:-docs/product-acceptance/${version}.json}"
if [[ ! -f "$acceptance_file" ]]; then
  echo "full product acceptance requires KIANA_PRODUCT_ACCEPTANCE_FILE or ${acceptance_file}" >&2
  exit 1
fi

PRODUCT_ACCEPTANCE_FILE="$acceptance_file" \
PRODUCT_ACCEPTANCE_OUT="$out" \
PRODUCT_ACCEPTANCE_VERSION="$version" \
"$(python_bin)" - <<'PY'
import json
import os
import shutil
import sys

source = os.environ["PRODUCT_ACCEPTANCE_FILE"]
out = os.environ["PRODUCT_ACCEPTANCE_OUT"]
version = os.environ["PRODUCT_ACCEPTANCE_VERSION"]

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

required_workflows = {
    "permission",
    "diff",
    "history",
    "onboarding",
    "resume",
    "settings",
}
workflows = set(report.get("workflows") or [])
checks = [
    report.get("schema") == "kiana.product-acceptance.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    isinstance(report.get("accepted_by"), str) and bool(report["accepted_by"].strip()),
    isinstance(report.get("accepted_at"), str) and bool(report["accepted_at"].strip()),
    isinstance(report.get("scope"), str) and bool(report["scope"].strip()),
    required_workflows.issubset(workflows),
]
if not all(checks):
    print("product acceptance file failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    sys.exit(1)

shutil.copyfile(source, out)
print(f"product acceptance accepted: {source} -> {out}")
PY
