#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"
out="${KIANA_PRODUCT_ACCEPTANCE_OUT:-target/product-acceptance/product-acceptance.json}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "product acceptance report requires python3 or python" >&2
    exit 1
  }
}

run_local_gate() {
  local description="$1"
  shift

  local output
  if output="$("$@" 2>&1)"; then
    printf '%s\n' "$output" >&2
    return 0
  fi

  if [[ "${KIANA_PRODUCT_ACCEPTANCE_ALLOW_LOCAL_RC_GATE_SKIP:-0}" == "1" ]] &&
    grep -Eq 'offline mode|unable to update registry|failed to select a version|download of .* failed|Timeout was reached' <<<"$output"; then
    printf 'local RC product acceptance gate skipped: %s\n%s\n' "$description" "$output" >&2
    PRODUCT_ACCEPTANCE_SKIPPED_GATES="${PRODUCT_ACCEPTANCE_SKIPPED_GATES:-}${PRODUCT_ACCEPTANCE_SKIPPED_GATES:+;}${description}"
    export PRODUCT_ACCEPTANCE_SKIPPED_GATES
    return 0
  fi

  printf '%s\n' "$output" >&2
  return 1
}

run_local_gate "product-shell-smoke" bash scripts/product-shell-smoke.sh
run_local_gate "kiana-query context_index" cargo test -p kiana-query --locked --offline context_index
run_local_gate "kiana-query context-cache-recovery" cargo test -p kiana-query --locked --offline persistent_context_index_recovers_from_corrupt_cache
run_local_gate "kiana-query context_search" cargo test -p kiana-query --locked --offline context_search
run_local_gate "kiana-commands context_index" cargo test -p kiana-commands --locked --offline context_index
run_local_gate "kiana-commands context-cache-recovery" cargo test -p kiana-commands --locked --offline context_index_json_recovers_corrupt_incremental_cache
run_local_gate "kiana-commands context_search" cargo test -p kiana-commands --locked --offline context_search

if [[ "$mode" == "--local-rc" ]]; then
  PRODUCT_ACCEPTANCE_OUT="$out" \
  PRODUCT_ACCEPTANCE_VERSION="$version" \
  PRODUCT_ACCEPTANCE_SKIPPED_GATES="${PRODUCT_ACCEPTANCE_SKIPPED_GATES:-}" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

skipped_gates = [
    item for item in os.environ.get("PRODUCT_ACCEPTANCE_SKIPPED_GATES", "").split(";") if item
]
status = "headless_smoke_only"
notes = ["Generated by scripts/product-acceptance-report.sh --local-rc"]
if skipped_gates:
    status = "headless_smoke_partial"
    notes.append(
        "Some local RC Cargo gates were skipped because the local offline Cargo registry cache was incomplete; rerun without KIANA_PRODUCT_ACCEPTANCE_ALLOW_LOCAL_RC_GATE_SKIP for a strict gate."
    )

report = {
    "schema": "kiana.product-acceptance.v1",
    "version": os.environ["PRODUCT_ACCEPTANCE_VERSION"],
    "status": status,
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "scope": "headless product-shell, app-server, and context-search smoke only; target-customer terminal acceptance is still required",
    "workflows": [
        "permission",
        "diff",
        "history",
        "onboarding",
        "resume",
        "settings",
        "app-server",
        "context-search",
        "context-cache-recovery",
    ],
    "notes": notes,
}
if skipped_gates:
    report["workflows"].append("local-rc-gate-skip")
    report["notes"].append("Skipped local RC gates: " + ", ".join(skipped_gates))
with open(os.environ["PRODUCT_ACCEPTANCE_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "product acceptance local RC report written to $out"
  exit 0
fi

acceptance_file="${KIANA_PRODUCT_ACCEPTANCE_FILE:-docs/product-acceptance/${version}.json}"
if [[ ! -f "$acceptance_file" ]]; then
  echo "full product acceptance requires KIANA_PRODUCT_ACCEPTANCE_FILE or ${acceptance_file}" >&2
  exit 1
fi

PRODUCT_ACCEPTANCE_FILE="$acceptance_file" \
PRODUCT_ACCEPTANCE_OUT="$out" \
PRODUCT_ACCEPTANCE_VERSION="$version" \
"$(python_bin)" - <<'PY'
import json
import os
import shutil
import sys

source = os.environ["PRODUCT_ACCEPTANCE_FILE"]
out = os.environ["PRODUCT_ACCEPTANCE_OUT"]
version = os.environ["PRODUCT_ACCEPTANCE_VERSION"]

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

required_workflows = {
    "permission",
    "diff",
    "history",
    "onboarding",
    "resume",
    "settings",
    "app-server",
    "context-search",
    "context-cache-recovery",
}
workflows = set(report.get("workflows") or [])
checks = [
    report.get("schema") == "kiana.product-acceptance.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    isinstance(report.get("accepted_by"), str) and bool(report["accepted_by"].strip()),
    isinstance(report.get("accepted_at"), str) and bool(report["accepted_at"].strip()),
    isinstance(report.get("scope"), str) and bool(report["scope"].strip()),
    required_workflows.issubset(workflows),
]
if not all(checks):
    print("product acceptance file failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    sys.exit(1)

shutil.copyfile(source, out)
print(f"product acceptance accepted: {source} -> {out}")
PY
