#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"
out="${KIANA_RELEASE_OPS_OUT:-target/release-ops/release-ops.json}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "release ops report requires python3 or python" >&2
    exit 1
  }
}

if [[ "$mode" == "--local-rc" ]]; then
  RELEASE_OPS_OUT="$out" \
    RELEASE_OPS_VERSION="$version" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

report = {
    "schema": "kiana.release-ops.v1",
    "version": os.environ["RELEASE_OPS_VERSION"],
    "status": "local_rc_only",
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "security_contact": "",
    "vulnerability_report_channel": "",
    "release_credentials_owner": "",
    "support_contact": "",
    "artifact_retention_days": 90,
    "log_retention_days": 30,
    "credential_review": {
        "status": "pending",
        "reviewed_by": "",
        "reviewed_at": "",
        "scope": "local RC only; production release credentials are not accepted",
    },
    "notes": ["Generated by scripts/release-ops-report.sh --local-rc"],
}
with open(os.environ["RELEASE_OPS_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "release ops local RC report written to $out"
  exit 0
fi

ops_file="${KIANA_RELEASE_OPS_FILE:-docs/release-ops/${version}.json}"
if [[ ! -f "$ops_file" ]]; then
  echo "full release ops proof requires KIANA_RELEASE_OPS_FILE or ${ops_file}" >&2
  exit 1
fi

RELEASE_OPS_FILE="$ops_file" \
RELEASE_OPS_OUT="$out" \
RELEASE_OPS_VERSION="$version" \
"$(python_bin)" - <<'PY'
import json
import os
import shutil
import sys

source = os.environ["RELEASE_OPS_FILE"]
out = os.environ["RELEASE_OPS_OUT"]
version = os.environ["RELEASE_OPS_VERSION"]

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

required_strings = [
    "accepted_by",
    "accepted_at",
    "security_contact",
    "vulnerability_report_channel",
    "release_credentials_owner",
    "support_contact",
]
placeholder_markers = (
    "todo",
    "tbd",
    "pending",
    "placeholder",
    "replace-me",
    "example.com",
    "example.test",
    "public issue",
)

def non_empty_string(key):
    value = report.get(key)
    return isinstance(value, str) and bool(value.strip())

def not_placeholder(key):
    value = report.get(key)
    if not isinstance(value, str):
        return False
    lowered = value.lower()
    return not any(marker in lowered for marker in placeholder_markers)

def review_not_placeholder(key):
    value = credential_review.get(key)
    if not isinstance(value, str):
        return False
    lowered = value.lower()
    return not any(marker in lowered for marker in placeholder_markers)

credential_review = report.get("credential_review")
if not isinstance(credential_review, dict):
    credential_review = {}

checks = [
    report.get("schema") == "kiana.release-ops.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    all(non_empty_string(key) for key in required_strings),
    all(not_placeholder(key) for key in required_strings),
    isinstance(report.get("artifact_retention_days"), int)
    and report["artifact_retention_days"] >= 90,
    isinstance(report.get("log_retention_days"), int)
    and report["log_retention_days"] >= 30,
    credential_review.get("status") == "accepted",
    isinstance(credential_review.get("reviewed_by"), str)
    and bool(credential_review["reviewed_by"].strip()),
    review_not_placeholder("reviewed_by"),
    isinstance(credential_review.get("reviewed_at"), str)
    and bool(credential_review["reviewed_at"].strip()),
    isinstance(credential_review.get("scope"), str)
    and bool(credential_review["scope"].strip()),
    review_not_placeholder("scope"),
]
if not all(checks):
    print("release ops file failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    sys.exit(1)

shutil.copyfile(source, out)
print(f"release ops accepted: {source} -> {out}")
PY
