#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mode="${1:-full}"
if [[ "$mode" != "full" && "$mode" != "--local-rc" ]]; then
  echo "usage: $0 [full|--local-rc]" >&2
  exit 2
fi

version="${VERSION:-$(tr -d '\r\n' < VERSION)}"
out="${KIANA_SOURCE_CONTROL_PROOF_OUT:-target/source-control/source-control.json}"
mkdir -p "$(dirname "$out")"

python_bin() {
  command -v python3 2>/dev/null || command -v python 2>/dev/null || {
    echo "source-control proof report requires python3 or python" >&2
    exit 1
  }
}

git_stdout() {
  git "$@" 2>/dev/null || true
}

expected_tag="v${version}"
commit="$(git_stdout rev-parse HEAD | tr -d '\r\n')"
origin_url="$(git_stdout remote get-url origin | tr -d '\r\n')"
if [[ -z "$origin_url" ]]; then
  origin_url="$(git_stdout remote | head -n 1 | tr -d '\r\n')"
fi
tagged_commit=""
if git tag --points-at HEAD 2>/dev/null | grep -Fxq "$expected_tag"; then
  tagged_commit="$commit"
fi

if [[ "$mode" == "--local-rc" ]]; then
  SOURCE_CONTROL_OUT="$out" \
  SOURCE_CONTROL_VERSION="$version" \
  SOURCE_CONTROL_TAG="$expected_tag" \
  SOURCE_CONTROL_COMMIT="${commit:-0000000000000000000000000000000000000000}" \
  SOURCE_CONTROL_TAGGED_COMMIT="${tagged_commit:-0000000000000000000000000000000000000000}" \
  SOURCE_CONTROL_REMOTE_URL="$origin_url" \
    "$(python_bin)" - <<'PY'
import json
import os
from datetime import datetime, timezone

commit = os.environ["SOURCE_CONTROL_COMMIT"]
tagged_commit = os.environ["SOURCE_CONTROL_TAGGED_COMMIT"]
remote_url = os.environ["SOURCE_CONTROL_REMOTE_URL"]
release_tag = os.environ["SOURCE_CONTROL_TAG"]
notes = [
    "Generated by scripts/source-control-proof-report.sh --local-rc",
    "Full commercial release requires release-owner accepted source-control proof from the pushed release repository.",
]
if not remote_url:
    notes.append("No production git remote was configured when this local RC proof draft was generated.")
if commit != tagged_commit:
    notes.append(f"HEAD was not tagged with {release_tag} when this local RC proof draft was generated.")

report = {
    "schema": "kiana.source-control-proof.v1",
    "version": os.environ["SOURCE_CONTROL_VERSION"],
    "status": "local_rc_only",
    "accepted": False,
    "accepted_by": "",
    "accepted_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "remote_url": remote_url,
    "commit": commit,
    "release_tag": release_tag,
    "tagged_commit": tagged_commit,
    "pushed": False,
    "reviewed": False,
    "notes": notes,
}
with open(os.environ["SOURCE_CONTROL_OUT"], "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY
  echo "source-control local RC proof written to $out"
  exit 0
fi

proof_file="${KIANA_SOURCE_CONTROL_PROOF_FILE:-docs/source-control/${version}.json}"
if [[ ! -f "$proof_file" ]]; then
  echo "full source-control proof requires KIANA_SOURCE_CONTROL_PROOF_FILE or ${proof_file}" >&2
  exit 1
fi

SOURCE_CONTROL_FILE="$proof_file" \
SOURCE_CONTROL_OUT="$out" \
SOURCE_CONTROL_VERSION="$version" \
SOURCE_CONTROL_TAG="$expected_tag" \
"$(python_bin)" - <<'PY'
import json
import os
import re
import shutil
import sys

source = os.environ["SOURCE_CONTROL_FILE"]
out = os.environ["SOURCE_CONTROL_OUT"]
version = os.environ["SOURCE_CONTROL_VERSION"]
expected_tag = os.environ["SOURCE_CONTROL_TAG"]

with open(source, "r", encoding="utf-8") as handle:
    report = json.load(handle)

placeholder_markers = (
    "todo",
    "tbd",
    "pending",
    "placeholder",
    "replace-me",
    "example.com",
    "example.test",
)

def filled(key):
    value = report.get(key)
    return isinstance(value, str) and bool(value.strip())

def not_placeholder(key):
    value = report.get(key)
    return isinstance(value, str) and not any(
        marker in value.lower() for marker in placeholder_markers
    )

remote_url = report.get("remote_url")
checks = [
    report.get("schema") == "kiana.source-control-proof.v1",
    report.get("version") == version,
    report.get("status") == "accepted",
    report.get("accepted") is True,
    filled("accepted_by"),
    filled("accepted_at"),
    filled("remote_url"),
    filled("commit"),
    filled("tagged_commit"),
    not_placeholder("accepted_by"),
    not_placeholder("remote_url"),
    isinstance(remote_url, str) and remote_url.startswith(("https://", "ssh://", "git@")),
    re.fullmatch(r"[0-9a-f]{40}", str(report.get("commit", ""))) is not None,
    re.fullmatch(r"[0-9a-f]{40}", str(report.get("tagged_commit", ""))) is not None,
    report.get("commit") == report.get("tagged_commit"),
    report.get("release_tag") == expected_tag,
    report.get("pushed") is True,
    report.get("reviewed") is True,
]
if not all(checks):
    print("source-control proof file failed commercial checks", file=sys.stderr)
    print(json.dumps(report, indent=2, sort_keys=True), file=sys.stderr)
    sys.exit(1)

if os.path.abspath(source) != os.path.abspath(out):
    shutil.copyfile(source, out)
print(f"source-control proof accepted: {source} -> {out}")
PY
