#!/usr/bin/env python3
"""Validate and regenerate the UI-09 schema lock and static Rust catalog.

The lock is intentionally small and deterministic.  JSON Schema files are the canonical wire
contract; this command checks their ids, hashes, examples, redaction rules and compatibility matrix,
then compares the generated Rust catalog with the lock.  ``--write`` is the only mutating mode.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "docs" / "schemas" / "ui"
LOCK_PATH = SCHEMA_ROOT / "schema-lock.v1.json"
MATRIX_PATH = SCHEMA_ROOT / "compatibility-matrix.v1.json"
VALIDATOR_PATH = ROOT / "scripts" / "validate-json-schema.py"

SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
HEX_DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")
SECRET_KEY = re.compile(r"(?:secret|token|password|passwd|api[_-]?key|authorization|private[_-]?key)", re.I)
ABSOLUTE_PATH = re.compile(r"^(?:/|[A-Za-z]:[\\/])")


class ContractError(RuntimeError):
    """A deterministic schema-lock violation."""


def reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ContractError(f"duplicate_json_key:{key}")
        result[key] = value
    return result


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=reject_duplicate_keys)
    except ContractError:
        raise
    except Exception as exc:  # noqa: BLE001
        raise ContractError(f"json_read_failed:{path.relative_to(ROOT)}:{exc}") from exc


def write_json(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def canonical_digest(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    return f"sha256:{hashlib.sha256(payload).hexdigest()}"


def safe_relative(raw: Any, field: str) -> Path:
    if not isinstance(raw, str) or not raw or "\0" in raw:
        raise ContractError(f"{field}_invalid")
    path = Path(raw)
    if path.is_absolute() or ".." in path.parts:
        raise ContractError(f"{field}_outside_registry")
    return path


def walk_values(value: Any, path: str = "$") -> list[tuple[str, Any]]:
    values = [(path, value)]
    if isinstance(value, dict):
        for key, child in value.items():
            values.extend(walk_values(child, f"{path}.{key}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            values.extend(walk_values(child, f"{path}[{index}]"))
    return values


def load_schema_validator() -> Any:
    spec = importlib.util.spec_from_file_location("kiana_schema_validator", VALIDATOR_PATH)
    if spec is None or spec.loader is None:
        raise ContractError("schema_validator_import_failed")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def generated_catalog(lock: dict[str, Any]) -> str:
    contracts = lock["contracts"]
    lines = [
        "//! Generated by scripts/validate-ui09-schemas.py --write; do not edit by hand.",
        "//!",
        "//! JSON Schema remains canonical. This catalog only exposes bounded metadata to clients.",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct UiSchemaContract {",
        "    pub id: &'static str,",
        "    pub rust_type: &'static str,",
        "    pub max_bytes: usize,",
        "    pub unknown_fields: &'static str,",
        "}",
        "",
        "pub const UI_SCHEMA_LOCK_SCHEMA: &str = \"kiana.ui-schema-lock.v1\";",
        "",
        "pub const UI_SCHEMA_CONTRACTS: &[UiSchemaContract] = &[",
    ]
    for contract in contracts:
        lines.extend(
            [
                "    UiSchemaContract {",
                f"        id: {contract['id']!r},".replace("'", '"'),
                f"        rust_type: {contract['rust_type']!r},".replace("'", '"'),
                f"        max_bytes: {contract['max_bytes']},",
                f"        unknown_fields: {contract['unknown_fields']!r},".replace("'", '"'),
                "    },",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            "pub fn schema_contract(id: &str) -> Option<&'static UiSchemaContract> {",
            "    UI_SCHEMA_CONTRACTS.iter().find(|contract| contract.id == id)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def validate_examples(
    validator: Any,
    schema: dict[str, Any],
    contract: dict[str, Any],
    schema_path: Path,
) -> None:
    valid_path = SCHEMA_ROOT / safe_relative(contract["valid_example"], "valid_example")
    unknown_path = SCHEMA_ROOT / safe_relative(contract["unknown_field_example"], "unknown_field_example")
    for path in (valid_path, unknown_path):
        if not path.is_file():
            raise ContractError(f"fixture_missing:{path.relative_to(ROOT)}")
        fixture = read_json(path)
        fixture_bytes = len(json.dumps(fixture, ensure_ascii=False, separators=(",", ":")).encode())
        if fixture_bytes > contract["max_bytes"]:
            raise ContractError(f"fixture_max_bytes_exceeded:{path.relative_to(ROOT)}")
        for location, value in walk_values(fixture):
            if isinstance(value, str):
                if ABSOLUTE_PATH.match(value) or "\\" in value and re.search(r"[A-Za-z]:", value):
                    raise ContractError(f"fixture_path:{path.relative_to(ROOT)}:{location}")
            if isinstance(value, dict):
                for key in value:
                    if SECRET_KEY.search(key):
                        raise ContractError(f"fixture_secret_key:{path.relative_to(ROOT)}:{location}.{key}")

    valid = read_json(valid_path)
    errors = validator.validate(schema, valid, schema, "$valid")
    if errors:
        raise ContractError(f"fixture_invalid:{valid_path.relative_to(ROOT)}:{errors[0]}")

    unknown = read_json(unknown_path)
    errors = validator.validate(schema, unknown, schema, "$unknown")
    if not errors:
        raise ContractError(f"unknown_field_not_rejected:{unknown_path.relative_to(ROOT)}")
    properties = schema.get("properties", {})
    unknown_keys = set(unknown) - set(properties)
    if not unknown_keys:
        raise ContractError(f"unknown_fixture_missing_top_level_field:{unknown_path.relative_to(ROOT)}")
    if schema.get("additionalProperties") is not False:
        raise ContractError(f"schema_not_strict:{schema_path.relative_to(ROOT)}")


def validate_lock(lock: dict[str, Any], validator: Any) -> list[dict[str, Any]]:
    required = {
        "$schema",
        "$id",
        "schema",
        "version",
        "source_of_truth",
        "canonical_owner",
        "generated_rust",
        "contracts",
    }
    if set(lock) != required:
        raise ContractError(f"lock_fields_invalid:{sorted(set(lock) ^ required)}")
    if lock["$schema"] != SCHEMA_DIALECT or lock["$id"] != lock["schema"]:
        raise ContractError("lock_header_invalid")
    if lock["schema"] != "kiana.ui-schema-lock.v1" or lock["version"] != "1.0":
        raise ContractError("lock_version_invalid")
    if lock["source_of_truth"] != "json_schema" or lock["canonical_owner"] != "kiana-protocol":
        raise ContractError("lock_owner_invalid")
    if not isinstance(lock["contracts"], list) or not lock["contracts"]:
        raise ContractError("lock_contracts_missing")

    contracts = lock["contracts"]
    ids = [entry.get("id") for entry in contracts if isinstance(entry, dict)]
    if any(not isinstance(identifier, str) for identifier in ids) or len(set(ids)) != len(ids):
        raise ContractError("lock_contract_ids_invalid")
    if ids != sorted(ids):
        raise ContractError("lock_contracts_not_sorted")

    for contract in contracts:
        fields = {
            "id",
            "version",
            "schema_file",
            "rust_type",
            "rust_source",
            "owner_crate",
            "unknown_fields",
            "max_bytes",
            "deprecated_fields",
            "valid_example",
            "unknown_field_example",
            "schema_sha256",
        }
        if not isinstance(contract, dict) or set(contract) != fields:
            identifier = contract.get("id", "<unknown>") if isinstance(contract, dict) else "<unknown>"
            raise ContractError(f"contract_fields_invalid:{identifier}")
        if contract["version"] != "1.0" or contract["owner_crate"] not in {
            "kiana-protocol",
            "kiana-client",
        }:
            raise ContractError(f"contract_header_invalid:{contract['id']}")
        if contract["unknown_fields"] != "deny":
            raise ContractError(f"contract_unknown_policy_invalid:{contract['id']}")
        if not isinstance(contract["max_bytes"], int) or contract["max_bytes"] <= 0:
            raise ContractError(f"contract_max_bytes_invalid:{contract['id']}")
        if contract["deprecated_fields"] != []:
            raise ContractError(f"contract_deprecated_fields_unreviewed:{contract['id']}")
        schema_path = SCHEMA_ROOT / safe_relative(contract["schema_file"], "schema_file")
        rust_path = ROOT / safe_relative(contract["rust_source"], "rust_source")
        if not schema_path.is_file() or not rust_path.is_file():
            raise ContractError(f"contract_source_missing:{contract['id']}")
        if contract["rust_type"] not in rust_path.read_text(encoding="utf-8"):
            raise ContractError(f"rust_type_missing:{contract['id']}")
        schema = read_json(schema_path)
        if not isinstance(schema, dict):
            raise ContractError(f"schema_root_invalid:{contract['id']}")
        if schema.get("$schema") != SCHEMA_DIALECT or schema.get("$id") != contract["id"]:
            raise ContractError(f"schema_identity_invalid:{contract['id']}")
        if schema.get("additionalProperties") is not False:
            raise ContractError(f"schema_unknown_policy_invalid:{contract['id']}")
        digest = canonical_digest(schema)
        if contract["schema_sha256"] != digest:
            raise ContractError(f"schema_hash_stale:{contract['id']}")
        schema_bytes = len(json.dumps(schema, ensure_ascii=False, separators=(",", ":")).encode())
        if schema_bytes > contract["max_bytes"]:
            raise ContractError(f"schema_max_bytes_exceeded:{contract['id']}")
        validate_examples(validator, schema, contract, schema_path)

    generated_path = ROOT / safe_relative(lock["generated_rust"], "generated_rust")
    if not generated_path.is_file():
        raise ContractError(f"generated_catalog_missing:{generated_path.relative_to(ROOT)}")
    if generated_path.read_text(encoding="utf-8") != generated_catalog(lock):
        raise ContractError("generated_catalog_stale")
    return contracts


def validate_matrix(matrix: dict[str, Any], contract_ids: set[str]) -> None:
    expected = {
        "$schema",
        "$id",
        "schema",
        "version",
        "same_version_policy",
        "unknown_major_policy",
        "unknown_command_policy",
        "rules",
        "negative_cases",
    }
    if set(matrix) != expected or matrix.get("$schema") != SCHEMA_DIALECT:
        raise ContractError("compatibility_matrix_header_invalid")
    if matrix.get("$id") != matrix.get("schema") or matrix.get("schema") != "kiana.ui-compatibility-matrix.v1":
        raise ContractError("compatibility_matrix_identity_invalid")
    if matrix.get("version") != "1.0" or matrix.get("same_version_policy") != "additive_only":
        raise ContractError("compatibility_matrix_policy_invalid")
    if matrix.get("unknown_major_policy") != "reject_before_decode" or matrix.get("unknown_command_policy") != "reject_with_schema_unsupported":
        raise ContractError("compatibility_matrix_fail_open")
    rules = matrix.get("rules")
    if not isinstance(rules, list) or not rules:
        raise ContractError("compatibility_matrix_rules_missing")
    seen: set[tuple[str, str]] = set()
    for rule in rules:
        if not isinstance(rule, dict):
            raise ContractError("compatibility_matrix_rule_invalid")
        pair = (rule.get("from"), rule.get("to"))
        if pair in seen or pair[0] not in contract_ids or pair[1] not in contract_ids:
            raise ContractError("compatibility_matrix_rule_reference_invalid")
        seen.add(pair)
        if pair[0] != pair[1] or rule.get("unknown_field_policy") != "deny" or rule.get("breaking_change") != "major_version_required":
            raise ContractError(f"compatibility_matrix_rule_not_fail_closed:{pair[0]}->{pair[1]}")
        if rule.get("old_client_reads_new_server") is not True or rule.get("new_server_reads_old_client") is not True:
            raise ContractError(f"compatibility_matrix_direction_missing:{pair[0]}")
    negative = matrix.get("negative_cases")
    if not isinstance(negative, list) or not negative or len({item.get("case_id") for item in negative}) != len(negative):
        raise ContractError("compatibility_matrix_negative_cases_invalid")
    if not {item.get("case_id") for item in negative} >= {
        "remove_required_field",
        "change_field_type",
        "unknown_major",
        "unknown_command",
    }:
        raise ContractError("compatibility_matrix_negative_coverage_missing")


def update_hashes(lock: dict[str, Any]) -> None:
    for contract in lock["contracts"]:
        schema = read_json(SCHEMA_ROOT / safe_relative(contract["schema_file"], "schema_file"))
        contract["schema_sha256"] = canonical_digest(schema)
    lock["contracts"] = sorted(lock["contracts"], key=lambda item: item["id"])


def run(write: bool) -> None:
    lock = read_json(LOCK_PATH)
    if not isinstance(lock, dict):
        raise ContractError("lock_root_invalid")
    if write:
        update_hashes(lock)
        write_json(LOCK_PATH, lock)
        generated_path = ROOT / safe_relative(lock["generated_rust"], "generated_rust")
        generated_path.write_text(generated_catalog(lock), encoding="utf-8")
    validator = load_schema_validator()
    contracts = validate_lock(lock, validator)
    matrix = read_json(MATRIX_PATH)
    if not isinstance(matrix, dict):
        raise ContractError("compatibility_matrix_root_invalid")
    validate_matrix(matrix, {contract["id"] for contract in contracts})
    if write:
        # Re-read generated output through the same read-only checks after writing.
        validate_lock(lock, validator)
    print(f"UI-09 schema lock valid: {len(contracts)} contracts; generated catalog is current")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="refresh hashes and generated Rust catalog")
    args = parser.parse_args()
    try:
        run(args.write)
    except ContractError as exc:
        print(f"UI-09 schema validation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
