[package]
name = "kiana-eventlog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
kiana-domain.workspace = true
kiana-ports.workspace = true
async-trait.workspace = true
libc.workspace = true
serde_json.workspace = true
tokio.workspace = true
